export function hasClass(el: any, cls: any): any;
export function addClass(el: any, cls: any): void;
export function removeClass(el: any, cls: any): void;
export function setStyle(element: any, styleName: any, value: any): void;
export function on(element: any, event: any, handler: any): void;
export function off(element: any, event: any, handler: any): void;
export function once(el: any, event: any, fn: any): void;
export function getStyle(element: any, styleName: any): any;
export function isScroll(el: any, vertical: any): any;
export function getScrollContainer(el: any, vertical: any): any;
export function isInContainer(el: any, container: any): boolean;
