declare const fontColor = "#304265";
declare const lineColor = "#C9CCD8";
declare const tooltipBgColor = "rgba(83,107,155,0.9)";
declare const tooltipShadowColor = "rgba(135,206,235,0.1)";
declare const mapBorderColor = "#eee";
declare const mapAreaColor = "#ddd";
declare const mapEmphasisAreaColor = "#FFA940";
declare const black = "#000";
declare const white = "#fff";
export { fontColor, lineColor, tooltipBgColor, tooltipShadowColor, mapBorderColor, mapAreaColor, mapEmphasisAreaColor, black, white };
declare const _default: {
    fontColor: string;
    lineColor: string;
    tooltipBgColor: string;
    tooltipShadowColor: string;
    mapBorderColor: string;
    mapAreaColor: string;
    mapEmphasisAreaColor: string;
    black: string;
    white: string;
};
export default _default;
