/**
 * 导出所有的属性模块实例对象
 */
import Dimension from "./dimension";
import GroupDimension from "./group-dimension";
import Metric from "./metric";
import Sort from "./sort";
import Filter from "./filter";
import Theme from "./theme";
import ChartTitle from "./title";
import Limit from "./limit";
import DimensionLimit from "./dimension-limit";
import Direction from "./direction";
import MetricRange from "./metric-range";
import DataLabel from "./data-label";
import MultipleDataLabel from "./multiple-data-label";
import Linkage from "./linkage";
import Download from "./download";
import OrderNumber from "./orderNumber";
import FreezeHead from "./freezeHead";
import Legend from "./legend";
import AxisX from "./axisx";
import ChartSwitch from "./chart-switch";
import WarningLine from "./warning-line";
import PaintCoatTheme from "./paint-coat-theme";
import PaintCoat from "./paint-coat";
import ElementCoat from "./element-coat";
import MultiMetricType from "./multi-metric-type";
import MultiRange from "./multi-range";
import MetricGroup from "./metric-group";
import FontSetting from "./font-setting";
import SplitLine from "./split-line";
import AxisYSet from "./axisy-set";
import DataZoom from "./datazoom";
import MapArea from "./map-area";
import MapDrill from "./map-drill";
import MapTheme from "./map-theme";
import MapDigitalSet from "./map-digital";
declare const _default: {
    MapDigitalSet: typeof MapDigitalSet;
    MapArea: typeof MapArea;
    MapDrill: typeof MapDrill;
    MapTheme: typeof MapTheme;
    Dimension: typeof Dimension;
    GroupDimension: typeof GroupDimension;
    Metric: typeof Metric;
    Theme: typeof Theme;
    ChartTitle: typeof ChartTitle;
    Sort: typeof Sort;
    Filter: typeof Filter;
    Limit: typeof Limit;
    DimensionLimit: typeof DimensionLimit;
    Direction: typeof Direction;
    MetricRange: typeof MetricRange;
    DataLabel: typeof DataLabel;
    MultipleDataLabel: typeof MultipleDataLabel;
    Linkage: typeof Linkage;
    Download: typeof Download;
    OrderNumber: typeof OrderNumber;
    FreezeHead: typeof FreezeHead;
    Legend: typeof Legend;
    AxisX: typeof AxisX;
    ChartSwitch: typeof ChartSwitch;
    WarningLine: typeof WarningLine;
    PaintCoatTheme: typeof PaintCoatTheme;
    PaintCoat: typeof PaintCoat;
    ElementCoat: typeof ElementCoat;
    MultiMetricType: typeof MultiMetricType;
    MultiRange: typeof MultiRange;
    MetricGroup: typeof MetricGroup;
    FontSetting: typeof FontSetting;
    SplitLine: typeof SplitLine;
    AxisYSet: typeof AxisYSet;
    DataZoom: typeof DataZoom;
};
export default _default;
