export declare enum ReportAction {
    ADDELEMENT = "addElement",
    GETREPORTDETAIL = "getReportDetail",
    GETREPORT = "getReport",
    SAVEREPORT = "saveReport",
    GETDATASOURCELIST = "getDataSourceList",
    GETDATASOURCE = "getDataSource",
    LOADDATASOURCE = "loadDataSource",
    LOADCHARTDATA = "loadChartData",
    SETCHARTLINKAGE = "setChartLinkage",
    SETFILTERPICKER = "setFilterPicker",
    REMOVEFILTERPICKER = "removeFilterPicker"
}
export declare enum ReportMutation {
    INITREPORT = "initReport",
    SETCHARTS = "setCharts",
    SETGLOBAL = "setGlobal",
    SETOBJECTID = "setObjectId",
    SETTITLE = "setTitle",
    SETREPORTTOP = "setReportTop",
    SETREPORTTITLE = "setReportTitle",
    SETACTIVECHART = "setActiveChart",
    CLEARACTIVECHART = "clearActiveChart",
    SETGLOBALFILTER = "setGlobalFilter",
    HANDLESORT = "handleSort",
    SETDRAGCHART = "setDragChart",
    SETDRAGFIELD = "setDragField",
    SETREPORTOPTIONS = "setReportOptions",
    CLEARCHARTRELATION = "clearChartRelation",
    RESIZECHARTVIEW = "resizeChartView",
    SETNUMBERFORMAT = "setNumberFormat",
    SETRESULTFILTER = "setResultFilter",
    SETDATEFORMAT = "setDateFormat",
    SETLASTDATASOURCE = "setLastDataSource",
    SETTABLEEXPORTDATA = "setTableExportData",
    DELETEMETRIC = "deleteMetric",
    SERINTROSTATE = "setIntroState",
    SETCHARTSDATA = "setChartsData",
    SETADVANCEDATASOURCE = "setAdvancedDataSource",
    SETDATAZOOMTHEMEGROBAL = "setDataZoomThemeGrobal"
}
