export declare enum BizDataType {
    Unspecified = -1,
    Bool = 1,
    DateTime = 5,
    Double = 7,
    Int = 9,
    Long = 11,
    String = 13,
    ShortString = 14,
    ByteArray = 20,
    Image = 23,
    File = 24,
    TimeSpan = 25,
    Unit = 26,
    UnitArray = 27,
    Html = 30,
    Xml = 32,
    BizObject = 40,
    BizObjectArray = 41,
    BizStructure = 42,
    BizStructureArray = 43,
    Association = 50,
    AssociationArray = 51,
    Map = 55,
    Address = 56,
    Formula = 57
}
