declare namespace _default {
    export { Dimension as H3Dimension };
    export { GroupDimension as H3GroupDimension };
    export { Metric as H3Metric };
    export { Sort as H3Sort };
    export { Filter as H3Filter };
    export { Theme as H3Theme };
    export { ChartTitle as H3ChartTitle };
    export { DimensionLimit as H3DimensionLimit };
    export { Limit as H3Limit };
    export { MetricRange as H3MetricRange };
    export { DataLabel as H3DataLabel };
    export { MultipleDataLabel as H3MultipleDataLabel };
    export { Linkage as H3Linkage };
    export { Download as H3Download };
    export { OrderNumber as H3OrderNumber };
    export { FreezeHead as H3FreezeHead };
    export { Legend as H3Legend };
    export { AxisX as H3AxisX };
    export { ChartSwitch as H3ChartSwitch };
    export { WarningLine as H3WarningLine };
    export { PaintCoatTheme as H3PaintCoatTheme };
    export { PaintCoat as H3PaintCoat };
    export { ElementCoat as H3ElementCoat };
    export { MultiMetricType as H3MultiMetricType };
    export { MultiRange as H3MultiRange };
    export { MetricGroup as H3MetricGroup };
    export { FontSetting as H3FontSetting };
    export { DataZoom as H3DataZoom };
}
export default _default;
import Sort from "./sort";
import PaintCoatTheme from "./paint-coat-theme";
import PaintCoat from "./paint-coat";
import ElementCoat from "./element-coat";
import FontSetting from "./font-setting";
