import bar from "./bar";
import pileBar from "./pile-bar";
import stripe from "./stripe";
import line from "./line";
import area from "./area";
import pie from "./pie";
import funnel from "./funnel";
import radar from "./radar";
import scatter from "./scatter";
import map from "./map";
declare const _default: {
    bar: typeof bar;
    pileBar: typeof pileBar;
    stripe: typeof stripe;
    line: typeof line;
    area: typeof area;
    pie: typeof pie;
    funnel: typeof funnel;
    radar: typeof radar;
    scatter: typeof scatter;
    map: typeof map;
};
export default _default;
